apiVersion: v1
kind: Service
metadata:
  name: captureorder
  labels:
    app: captureorder
    name: captureorder
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: captureorder
  type: LoadBalancer