apiVersion: v1
kind: Service
metadata:
  name: captureordervsts
  labels:
    app: captureordervsts
    name: captureordervsts
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: captureordervsts
  type: LoadBalancer
