apiVersion: v1
kind: Service
metadata:
  name: fullfillorder
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: fullfillorder